# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import Jigen_pb2 as Jigen__pb2


class StoreCollectionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCollections = channel.unary_unary(
                '/jigen.StoreCollectionService/ListCollections',
                request_serializer=Jigen__pb2.CollectionKey.SerializeToString,
                response_deserializer=Jigen__pb2.ListCollectionResult.FromString,
                _registered_method=True)
        self.GetContent = channel.unary_unary(
                '/jigen.StoreCollectionService/GetContent',
                request_serializer=Jigen__pb2.ItemKey.SerializeToString,
                response_deserializer=Jigen__pb2.RawContentResult.FromString,
                _registered_method=True)
        self.GetEmbedding = channel.unary_unary(
                '/jigen.StoreCollectionService/GetEmbedding',
                request_serializer=Jigen__pb2.ItemKey.SerializeToString,
                response_deserializer=Jigen__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.SetDocument = channel.unary_unary(
                '/jigen.StoreCollectionService/SetDocument',
                request_serializer=Jigen__pb2.Document.SerializeToString,
                response_deserializer=Jigen__pb2.Result.FromString,
                _registered_method=True)
        self.SetVector = channel.unary_unary(
                '/jigen.StoreCollectionService/SetVector',
                request_serializer=Jigen__pb2.Vector.SerializeToString,
                response_deserializer=Jigen__pb2.Result.FromString,
                _registered_method=True)
        self.SetVectors = channel.stream_unary(
                '/jigen.StoreCollectionService/SetVectors',
                request_serializer=Jigen__pb2.Vector.SerializeToString,
                response_deserializer=Jigen__pb2.IngestResult.FromString,
                _registered_method=True)
        self.SetDocuments = channel.stream_unary(
                '/jigen.StoreCollectionService/SetDocuments',
                request_serializer=Jigen__pb2.Document.SerializeToString,
                response_deserializer=Jigen__pb2.IngestResult.FromString,
                _registered_method=True)
        self.SearchVector = channel.unary_unary(
                '/jigen.StoreCollectionService/SearchVector',
                request_serializer=Jigen__pb2.SearchVectorRequest.SerializeToString,
                response_deserializer=Jigen__pb2.SearchVectorResponse.FromString,
                _registered_method=True)
        self.SearchDocument = channel.unary_unary(
                '/jigen.StoreCollectionService/SearchDocument',
                request_serializer=Jigen__pb2.SearchDocumentRequest.SerializeToString,
                response_deserializer=Jigen__pb2.SearchVectorResponse.FromString,
                _registered_method=True)
        self.DeleteVector = channel.unary_unary(
                '/jigen.StoreCollectionService/DeleteVector',
                request_serializer=Jigen__pb2.ItemKey.SerializeToString,
                response_deserializer=Jigen__pb2.Result.FromString,
                _registered_method=True)
        self.GetAllKeys = channel.unary_unary(
                '/jigen.StoreCollectionService/GetAllKeys',
                request_serializer=Jigen__pb2.CollectionKey.SerializeToString,
                response_deserializer=Jigen__pb2.KeysResult.FromString,
                _registered_method=True)
        self.StreamKeys = channel.unary_stream(
                '/jigen.StoreCollectionService/StreamKeys',
                request_serializer=Jigen__pb2.StreamKeysRequest.SerializeToString,
                response_deserializer=Jigen__pb2.KeysResult.FromString,
                _registered_method=True)
        self.Contains = channel.unary_unary(
                '/jigen.StoreCollectionService/Contains',
                request_serializer=Jigen__pb2.ItemKey.SerializeToString,
                response_deserializer=Jigen__pb2.Result.FromString,
                _registered_method=True)
        self.Clear = channel.unary_unary(
                '/jigen.StoreCollectionService/Clear',
                request_serializer=Jigen__pb2.CollectionKey.SerializeToString,
                response_deserializer=Jigen__pb2.Result.FromString,
                _registered_method=True)
        self.Count = channel.unary_unary(
                '/jigen.StoreCollectionService/Count',
                request_serializer=Jigen__pb2.CollectionKey.SerializeToString,
                response_deserializer=Jigen__pb2.CountResult.FromString,
                _registered_method=True)
        self.CalculateEmbeddings = channel.unary_unary(
                '/jigen.StoreCollectionService/CalculateEmbeddings',
                request_serializer=Jigen__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=Jigen__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.CalculateEmbeddingsBatch = channel.unary_unary(
                '/jigen.StoreCollectionService/CalculateEmbeddingsBatch',
                request_serializer=Jigen__pb2.EmbeddingBatchRequest.SerializeToString,
                response_deserializer=Jigen__pb2.EmbeddingBatchResponse.FromString,
                _registered_method=True)
        self.CalculateImageEmbedding = channel.unary_unary(
                '/jigen.StoreCollectionService/CalculateImageEmbedding',
                request_serializer=Jigen__pb2.ImageEmbeddingRequest.SerializeToString,
                response_deserializer=Jigen__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.CalculateImageEmbeddingBatch = channel.unary_unary(
                '/jigen.StoreCollectionService/CalculateImageEmbeddingBatch',
                request_serializer=Jigen__pb2.ImageEmbeddingBatchRequest.SerializeToString,
                response_deserializer=Jigen__pb2.EmbeddingBatchResponse.FromString,
                _registered_method=True)
        self.CalculateImageTileEmbeddings = channel.unary_unary(
                '/jigen.StoreCollectionService/CalculateImageTileEmbeddings',
                request_serializer=Jigen__pb2.ImageEmbeddingRequest.SerializeToString,
                response_deserializer=Jigen__pb2.ImageTileEmbeddingsResponse.FromString,
                _registered_method=True)
        self.GetCollectionInfo = channel.unary_unary(
                '/jigen.StoreCollectionService/GetCollectionInfo',
                request_serializer=Jigen__pb2.CollectionKey.SerializeToString,
                response_deserializer=Jigen__pb2.CollectionInfoResponse.FromString,
                _registered_method=True)
        self.GetCollectionsInfo = channel.unary_unary(
                '/jigen.StoreCollectionService/GetCollectionsInfo',
                request_serializer=Jigen__pb2.CollectionKey.SerializeToString,
                response_deserializer=Jigen__pb2.CollectionsInfoResponse.FromString,
                _registered_method=True)
        self.GetCollectionGraph = channel.unary_unary(
                '/jigen.StoreCollectionService/GetCollectionGraph',
                request_serializer=Jigen__pb2.GetGraphRequest.SerializeToString,
                response_deserializer=Jigen__pb2.GraphSnapshotResponse.FromString,
                _registered_method=True)
        self.SearchFilter = channel.unary_unary(
                '/jigen.StoreCollectionService/SearchFilter',
                request_serializer=Jigen__pb2.SearchFilterRequest.SerializeToString,
                response_deserializer=Jigen__pb2.SearchVectorResponse.FromString,
                _registered_method=True)
        self.AppendDocument = channel.unary_unary(
                '/jigen.StoreCollectionService/AppendDocument',
                request_serializer=Jigen__pb2.Document.SerializeToString,
                response_deserializer=Jigen__pb2.Result.FromString,
                _registered_method=True)
        self.AppendVector = channel.unary_unary(
                '/jigen.StoreCollectionService/AppendVector',
                request_serializer=Jigen__pb2.Vector.SerializeToString,
                response_deserializer=Jigen__pb2.Result.FromString,
                _registered_method=True)
        self.SetRawVector = channel.unary_unary(
                '/jigen.StoreCollectionService/SetRawVector',
                request_serializer=Jigen__pb2.Vector.SerializeToString,
                response_deserializer=Jigen__pb2.Result.FromString,
                _registered_method=True)
        self.Transaction = channel.stream_stream(
                '/jigen.StoreCollectionService/Transaction',
                request_serializer=Jigen__pb2.TransactionOp.SerializeToString,
                response_deserializer=Jigen__pb2.TransactionResult.FromString,
                _registered_method=True)


class StoreCollectionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedding(self, request, context):
        """Stored full-precision embedding of a key. Empty Embeddings when the key
        does not exist or the entry was stored without a vector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVectors(self, request_iterator, context):
        """Bulk ingestion: one call, many entries. Avoids the per-item round trip of
        SetVector/SetDocument; SetDocuments also batches the server-side embedding
        calculation of the streamed sentences.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDocuments(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamKeys(self, request, context):
        """Keys in chunks over a server stream: use instead of GetAllKeys on large
        collections, where a single KeysResult would exceed the message size cap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Contains(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Count(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateEmbeddingsBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateImageEmbedding(self, request, context):
        """── Direct image embedding: raw image bytes in, vision model vector out ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateImageEmbeddingBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateImageTileEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionInfo(self, request, context):
        """── Collection metadata ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionsInfo(self, request, context):
        """Full details of all collections in a database (the Collection field of
        the request is ignored; only Database is used).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchFilter(self, request, context):
        """── Filter-only search (no query vector, no similarity scores) ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendDocument(self, request, context):
        """── Append-only variants: reject when the key already exists, unlike
        SetDocument/SetVector which upsert. ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRawVector(self, request, context):
        """── Raw vector storage without server-side normalization or processing. ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transaction(self, request_iterator, context):
        """── Multi-entry atomic transaction with WAL durability guarantees.
        Bidirectional stream: client sends Begin → Append*/Delete → Commit/Rollback;
        server acknowledges each step and commits atomically on Commit. ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreCollectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=Jigen__pb2.CollectionKey.FromString,
                    response_serializer=Jigen__pb2.ListCollectionResult.SerializeToString,
            ),
            'GetContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContent,
                    request_deserializer=Jigen__pb2.ItemKey.FromString,
                    response_serializer=Jigen__pb2.RawContentResult.SerializeToString,
            ),
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=Jigen__pb2.ItemKey.FromString,
                    response_serializer=Jigen__pb2.EmbeddingResponse.SerializeToString,
            ),
            'SetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDocument,
                    request_deserializer=Jigen__pb2.Document.FromString,
                    response_serializer=Jigen__pb2.Result.SerializeToString,
            ),
            'SetVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVector,
                    request_deserializer=Jigen__pb2.Vector.FromString,
                    response_serializer=Jigen__pb2.Result.SerializeToString,
            ),
            'SetVectors': grpc.stream_unary_rpc_method_handler(
                    servicer.SetVectors,
                    request_deserializer=Jigen__pb2.Vector.FromString,
                    response_serializer=Jigen__pb2.IngestResult.SerializeToString,
            ),
            'SetDocuments': grpc.stream_unary_rpc_method_handler(
                    servicer.SetDocuments,
                    request_deserializer=Jigen__pb2.Document.FromString,
                    response_serializer=Jigen__pb2.IngestResult.SerializeToString,
            ),
            'SearchVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVector,
                    request_deserializer=Jigen__pb2.SearchVectorRequest.FromString,
                    response_serializer=Jigen__pb2.SearchVectorResponse.SerializeToString,
            ),
            'SearchDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocument,
                    request_deserializer=Jigen__pb2.SearchDocumentRequest.FromString,
                    response_serializer=Jigen__pb2.SearchVectorResponse.SerializeToString,
            ),
            'DeleteVector': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVector,
                    request_deserializer=Jigen__pb2.ItemKey.FromString,
                    response_serializer=Jigen__pb2.Result.SerializeToString,
            ),
            'GetAllKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllKeys,
                    request_deserializer=Jigen__pb2.CollectionKey.FromString,
                    response_serializer=Jigen__pb2.KeysResult.SerializeToString,
            ),
            'StreamKeys': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamKeys,
                    request_deserializer=Jigen__pb2.StreamKeysRequest.FromString,
                    response_serializer=Jigen__pb2.KeysResult.SerializeToString,
            ),
            'Contains': grpc.unary_unary_rpc_method_handler(
                    servicer.Contains,
                    request_deserializer=Jigen__pb2.ItemKey.FromString,
                    response_serializer=Jigen__pb2.Result.SerializeToString,
            ),
            'Clear': grpc.unary_unary_rpc_method_handler(
                    servicer.Clear,
                    request_deserializer=Jigen__pb2.CollectionKey.FromString,
                    response_serializer=Jigen__pb2.Result.SerializeToString,
            ),
            'Count': grpc.unary_unary_rpc_method_handler(
                    servicer.Count,
                    request_deserializer=Jigen__pb2.CollectionKey.FromString,
                    response_serializer=Jigen__pb2.CountResult.SerializeToString,
            ),
            'CalculateEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateEmbeddings,
                    request_deserializer=Jigen__pb2.EmbeddingRequest.FromString,
                    response_serializer=Jigen__pb2.EmbeddingResponse.SerializeToString,
            ),
            'CalculateEmbeddingsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateEmbeddingsBatch,
                    request_deserializer=Jigen__pb2.EmbeddingBatchRequest.FromString,
                    response_serializer=Jigen__pb2.EmbeddingBatchResponse.SerializeToString,
            ),
            'CalculateImageEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateImageEmbedding,
                    request_deserializer=Jigen__pb2.ImageEmbeddingRequest.FromString,
                    response_serializer=Jigen__pb2.EmbeddingResponse.SerializeToString,
            ),
            'CalculateImageEmbeddingBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateImageEmbeddingBatch,
                    request_deserializer=Jigen__pb2.ImageEmbeddingBatchRequest.FromString,
                    response_serializer=Jigen__pb2.EmbeddingBatchResponse.SerializeToString,
            ),
            'CalculateImageTileEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateImageTileEmbeddings,
                    request_deserializer=Jigen__pb2.ImageEmbeddingRequest.FromString,
                    response_serializer=Jigen__pb2.ImageTileEmbeddingsResponse.SerializeToString,
            ),
            'GetCollectionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionInfo,
                    request_deserializer=Jigen__pb2.CollectionKey.FromString,
                    response_serializer=Jigen__pb2.CollectionInfoResponse.SerializeToString,
            ),
            'GetCollectionsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionsInfo,
                    request_deserializer=Jigen__pb2.CollectionKey.FromString,
                    response_serializer=Jigen__pb2.CollectionsInfoResponse.SerializeToString,
            ),
            'GetCollectionGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionGraph,
                    request_deserializer=Jigen__pb2.GetGraphRequest.FromString,
                    response_serializer=Jigen__pb2.GraphSnapshotResponse.SerializeToString,
            ),
            'SearchFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchFilter,
                    request_deserializer=Jigen__pb2.SearchFilterRequest.FromString,
                    response_serializer=Jigen__pb2.SearchVectorResponse.SerializeToString,
            ),
            'AppendDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendDocument,
                    request_deserializer=Jigen__pb2.Document.FromString,
                    response_serializer=Jigen__pb2.Result.SerializeToString,
            ),
            'AppendVector': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendVector,
                    request_deserializer=Jigen__pb2.Vector.FromString,
                    response_serializer=Jigen__pb2.Result.SerializeToString,
            ),
            'SetRawVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRawVector,
                    request_deserializer=Jigen__pb2.Vector.FromString,
                    response_serializer=Jigen__pb2.Result.SerializeToString,
            ),
            'Transaction': grpc.stream_stream_rpc_method_handler(
                    servicer.Transaction,
                    request_deserializer=Jigen__pb2.TransactionOp.FromString,
                    response_serializer=Jigen__pb2.TransactionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jigen.StoreCollectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jigen.StoreCollectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StoreCollectionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/ListCollections',
            Jigen__pb2.CollectionKey.SerializeToString,
            Jigen__pb2.ListCollectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/GetContent',
            Jigen__pb2.ItemKey.SerializeToString,
            Jigen__pb2.RawContentResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/GetEmbedding',
            Jigen__pb2.ItemKey.SerializeToString,
            Jigen__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/SetDocument',
            Jigen__pb2.Document.SerializeToString,
            Jigen__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/SetVector',
            Jigen__pb2.Vector.SerializeToString,
            Jigen__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVectors(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/jigen.StoreCollectionService/SetVectors',
            Jigen__pb2.Vector.SerializeToString,
            Jigen__pb2.IngestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDocuments(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/jigen.StoreCollectionService/SetDocuments',
            Jigen__pb2.Document.SerializeToString,
            Jigen__pb2.IngestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/SearchVector',
            Jigen__pb2.SearchVectorRequest.SerializeToString,
            Jigen__pb2.SearchVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/SearchDocument',
            Jigen__pb2.SearchDocumentRequest.SerializeToString,
            Jigen__pb2.SearchVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/DeleteVector',
            Jigen__pb2.ItemKey.SerializeToString,
            Jigen__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/GetAllKeys',
            Jigen__pb2.CollectionKey.SerializeToString,
            Jigen__pb2.KeysResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jigen.StoreCollectionService/StreamKeys',
            Jigen__pb2.StreamKeysRequest.SerializeToString,
            Jigen__pb2.KeysResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Contains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/Contains',
            Jigen__pb2.ItemKey.SerializeToString,
            Jigen__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/Clear',
            Jigen__pb2.CollectionKey.SerializeToString,
            Jigen__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/Count',
            Jigen__pb2.CollectionKey.SerializeToString,
            Jigen__pb2.CountResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/CalculateEmbeddings',
            Jigen__pb2.EmbeddingRequest.SerializeToString,
            Jigen__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateEmbeddingsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/CalculateEmbeddingsBatch',
            Jigen__pb2.EmbeddingBatchRequest.SerializeToString,
            Jigen__pb2.EmbeddingBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateImageEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/CalculateImageEmbedding',
            Jigen__pb2.ImageEmbeddingRequest.SerializeToString,
            Jigen__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateImageEmbeddingBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/CalculateImageEmbeddingBatch',
            Jigen__pb2.ImageEmbeddingBatchRequest.SerializeToString,
            Jigen__pb2.EmbeddingBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateImageTileEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/CalculateImageTileEmbeddings',
            Jigen__pb2.ImageEmbeddingRequest.SerializeToString,
            Jigen__pb2.ImageTileEmbeddingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/GetCollectionInfo',
            Jigen__pb2.CollectionKey.SerializeToString,
            Jigen__pb2.CollectionInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/GetCollectionsInfo',
            Jigen__pb2.CollectionKey.SerializeToString,
            Jigen__pb2.CollectionsInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/GetCollectionGraph',
            Jigen__pb2.GetGraphRequest.SerializeToString,
            Jigen__pb2.GraphSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/SearchFilter',
            Jigen__pb2.SearchFilterRequest.SerializeToString,
            Jigen__pb2.SearchVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/AppendDocument',
            Jigen__pb2.Document.SerializeToString,
            Jigen__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/AppendVector',
            Jigen__pb2.Vector.SerializeToString,
            Jigen__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRawVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jigen.StoreCollectionService/SetRawVector',
            Jigen__pb2.Vector.SerializeToString,
            Jigen__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transaction(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/jigen.StoreCollectionService/Transaction',
            Jigen__pb2.TransactionOp.SerializeToString,
            Jigen__pb2.TransactionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
