/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'auth-callback',
    path: '/auth/callback',
    component: 'layout.blank$view.auth-callback',
    meta: {
      title: 'auth-callback',
      i18nKey: 'route.auth-callback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'collections',
    path: '/collections',
    component: 'layout.base$view.collections',
    meta: {
      title: 'collections',
      i18nKey: 'route.collections',
      icon: 'mdi:folder-multiple-outline',
      order: 3
    }
  },
  {
    name: 'databases',
    path: '/databases',
    component: 'layout.base$view.databases',
    meta: {
      title: 'databases',
      i18nKey: 'route.databases',
      icon: 'mdi:database-outline',
      order: 2
    }
  },
  {
    name: 'graph-explorer',
    path: '/graph-explorer',
    component: 'layout.base$view.graph-explorer',
    meta: {
      title: 'graph-explorer',
      i18nKey: 'route.graph-explorer',
      icon: 'mdi:graph-outline',
      order: 5,
      keepAlive: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'overview',
    path: '/overview',
    component: 'layout.base$view.overview',
    meta: {
      title: 'overview',
      i18nKey: 'route.overview',
      icon: 'mdi:view-dashboard-outline',
      order: 1
    }
  },
  {
    name: 'security',
    path: '/security',
    component: 'layout.base$view.security',
    meta: {
      title: 'security',
      i18nKey: 'route.security',
      icon: 'mdi:shield-account-outline',
      order: 6
    }
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: 'settings',
      i18nKey: 'route.settings',
      icon: 'mdi:cog-outline',
      order: 7
    }
  },
  {
    name: 'workbench',
    path: '/workbench',
    component: 'layout.base$view.workbench',
    meta: {
      title: 'workbench',
      i18nKey: 'route.workbench',
      icon: 'mdi:database-search-outline',
      order: 4,
      keepAlive: true
    }
  }
];
